project:
  type: website
  output-dir: docs

website:
  title: "Breckin Hadley"
  navbar:
   left:
     - href: index.qmd
       text: Home
     - Mini_Project1.qmd
     - Mapping.qmd

format:
  html:
    theme: lex
    css: styles.css

